name: squeeze
version: 1.0.0+1
publish_to: none
description: Cleaning services.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: 4.3.8
  get_storage: 2.0.3
  get_cli: 1.6.0

  google_maps_flutter: ^2.0.6
  geolocator: ^7.4.0
  google_place: ^0.4.3
  google_geocoding: ^0.2.0
  google_fonts: 2.1.0

  graphql_flutter: ^5.0.0
  gql_dio_link: ^0.1.0
  dio_cookie_manager: ^2.0.0

  supercharged: 2.0.0
  fluttericon: 2.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  logger: any
  flutter_native_splash: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  pin_code_fields: ^7.3.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  image: assets/images/squeeze.png
  color: "# dffe02"
  android_disable_fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/