const PHONE_ALREADY_IN_USE = "phone number already in use";

//types
const ICONIC_OPTIONS_SELECT = 'ICONIC_OPTIONS_SELECT';
const OPTIONS_SELECT = 'OPTIONS_SELECT';
const ADDRESS_MODEL = 'ADDRESS_MODEL';
const TEXTAREA = 'TEXTAREA';
const PAYMENT_METHOD = 'PAYMENT_METHOD';
