///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String jsonKeyRegisterInputRegisterRegisterInputData =
    "registerRegisterInputData";
const String jsonKeyRegisterInputRegisterRegisterInputDataEmail = "email";
const String jsonKeyRegisterInputRegisterRegisterInputDataPhoneNumber =
    "phoneNumber";
const String jsonKeyRegisterInputRegisterRegisterInputDataFirstName =
    "firstName";
const String jsonKeyRegisterInputRegisterRegisterInputDataLastName = "lastName";

class RegisterInputRegisterRegisterInputData {
/*
{
  "email": "ahmad@dataa.com",
  "phoneNumber": "00971525626561",
  "firstName": "asd",
  "lastName": "asd"
}
*/

  String? email;
  String? phoneNumber;
  String? firstName;
  String? lastName;

  RegisterInputRegisterRegisterInputData({
    this.email,
    this.phoneNumber,
    this.firstName,
    this.lastName,
  });

  RegisterInputRegisterRegisterInputData.fromJson(Map<String, dynamic> json) {
    email =
        json[jsonKeyRegisterInputRegisterRegisterInputDataEmail]?.toString();
    phoneNumber = json[jsonKeyRegisterInputRegisterRegisterInputDataPhoneNumber]
        ?.toString();
    firstName = json[jsonKeyRegisterInputRegisterRegisterInputDataFirstName]
        ?.toString();
    lastName =
        json[jsonKeyRegisterInputRegisterRegisterInputDataLastName]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[jsonKeyRegisterInputRegisterRegisterInputDataEmail] = email;
    data[jsonKeyRegisterInputRegisterRegisterInputDataPhoneNumber] =
        phoneNumber;
    data[jsonKeyRegisterInputRegisterRegisterInputDataFirstName] = firstName;
    data[jsonKeyRegisterInputRegisterRegisterInputDataLastName] = lastName;
    return data;
  }
}

class RegisterInput {
/*
{
  "registerRegisterInputData": {
    "email": "ahmad@dataa.com",
    "phoneNumber": "00971525626561",
    "firstName": "asd",
    "lastName": "asd"
  }
}
*/

  RegisterInputRegisterRegisterInputData? registerRegisterInputData;

  RegisterInput({
    this.registerRegisterInputData,
  });

  RegisterInput.fromJson(Map<String, dynamic> json) {
    registerRegisterInputData =
        (json[jsonKeyRegisterInputRegisterRegisterInputData] != null &&
                (json[jsonKeyRegisterInputRegisterRegisterInputData] is Map))
            ? RegisterInputRegisterRegisterInputData.fromJson(
                json[jsonKeyRegisterInputRegisterRegisterInputData])
            : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (registerRegisterInputData != null) {
      data[jsonKeyRegisterInputRegisterRegisterInputData] =
          registerRegisterInputData!.toJson();
    }
    return data;
  }
}
